import { useState } from 'react';
import { Alert, Platform, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { supabase } from './lib/supabase';
import { colors } from './theme';

export function AuthScreen() {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [confirmPassword,setConfirmPassword]=useState(''); const [name,setName]=useState(''); const [signup,setSignup]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<{tone:'success'|'error';text:string}|null>(null);
  const submit=async()=>{if(!supabase||!email.trim()||!password)return setMessage({tone:'error',text:'Enter your email address and password.'});if(signup&&!name.trim())return setMessage({tone:'error',text:'Enter a display name.'});if(signup&&password!==confirmPassword)return setMessage({tone:'error',text:'The passwords do not match.'});setBusy(true);setMessage(null);const result=signup?await supabase.auth.signUp({email:email.trim(),password,options:{data:{display_name:name.trim()},emailRedirectTo:confirmationRedirect()}}):await supabase.auth.signInWithPassword({email:email.trim(),password});setBusy(false);if(result.error)return setMessage({tone:'error',text:result.error.message});if(signup&&!result.data.session){setPassword('');setConfirmPassword('');setMessage({tone:'success',text:`Account created. We sent a confirmation link to ${email.trim()}. Open it to verify your email, then sign in.`});}};
  const toggleMode=()=>{setSignup(value=>!value);setPassword('');setConfirmPassword('');setMessage(null);};
  return <SafeAreaView style={styles.safe}><LinearGradient colors={[colors.navy,'#294C7E']} style={styles.authHero}><Text style={styles.shield}>🛡️</Text><Text style={styles.authTitle}>HOME <Text style={{color:'#A7D66D'}}>HERO</Text></Text><Text style={styles.authLead}>Strong habits today. Success tomorrow.</Text></LinearGradient><View style={styles.form}><Text style={styles.heading}>{signup?'Create your hero account':'Welcome back'}</Text>{message&&<View accessibilityRole="alert" style={[styles.message,message.tone==='success'?styles.successMessage:styles.errorMessage]}><Text style={[styles.messageText,message.tone==='success'?styles.successText:styles.errorText]}>{message.text}</Text></View>}{signup&&<TextInput placeholder="Display name" value={name} onChangeText={setName} style={styles.input}/>}<TextInput placeholder="Email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} style={styles.input}/><TextInput placeholder="Password" secureTextEntry value={password} onChangeText={setPassword} style={styles.input}/>{signup&&<TextInput placeholder="Confirm password" secureTextEntry value={confirmPassword} onChangeText={setConfirmPassword} style={styles.input}/>}<Pressable onPress={submit} disabled={busy} style={[styles.primary,busy&&styles.primaryDisabled]}><Text style={styles.primaryText}>{busy?(signup?'Creating account…':'Signing in…'):signup?'Create account':'Sign in'}</Text></Pressable><Pressable onPress={toggleMode}><Text style={styles.link}>{signup?'Already have an account? Sign in':'New family? Create an account'}</Text></Pressable></View></SafeAreaView>;
}

function confirmationRedirect(){if(Platform.OS==='web'&&typeof window!=='undefined')return window.location.origin;return 'homehero://';}

export function OnboardingScreen({refresh}:{refresh:()=>Promise<void>}) {
  const [mode,setMode]=useState<'parent'|'child'>('parent'); const [value,setValue]=useState(''); const [birthDate,setBirthDate]=useState(''); const [busy,setBusy]=useState(false);
  const submit=async()=>{if(!supabase||!value.trim())return;if(mode==='child'&&!isValidBirthDate(birthDate))return Alert.alert('Valid birth date required','Enter a real date as YYYY-MM-DD. Heroes must be between 3 and 18 years old.');setBusy(true);const {error}=mode==='parent'?await supabase.rpc('create_parent_household',{p_name:value.trim(),p_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone}):await supabase.rpc('join_household_as_child',{p_invite_code:value.trim(),p_date_of_birth:birthDate});setBusy(false);if(error)Alert.alert('Could not continue',error.message);else await refresh();};
  return <SafeAreaView style={styles.safe}><View style={styles.onboard}><Text style={styles.shield}>🛡️</Text><Text style={styles.heading}>Build your hero party</Text><Text style={styles.copy}>Choose how this account will use Home Hero.</Text><View style={styles.segment}>{(['parent','child'] as const).map(item=><Pressable key={item} onPress={()=>setMode(item)} style={[styles.segmentItem,mode===item&&styles.segmentActive]}><Text style={[styles.segmentText,mode===item&&styles.segmentTextActive]}>{item==='parent'?'Party Leader':'Hero'}</Text></Pressable>)}</View><TextInput value={value} onChangeText={setValue} autoCapitalize={mode==='child'?'characters':'words'} placeholder={mode==='parent'?'Family name':'8-character family code'} style={styles.input}/>{mode==='child'&&<><TextInput value={birthDate} onChangeText={setBirthDate} keyboardType="numbers-and-punctuation" placeholder="Birth date · YYYY-MM-DD" style={styles.input}/><Text style={styles.privacyNote}>Used only to show age-appropriate quests.</Text></>}<Pressable onPress={submit} disabled={busy} style={styles.primary}><Text style={styles.primaryText}>{busy?'Setting up…':mode==='parent'?'Create family':'Join family'}</Text></Pressable><Pressable onPress={()=>supabase?.auth.signOut()}><Text style={styles.link}>Sign out</Text></Pressable></View></SafeAreaView>;
}

function isValidBirthDate(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(`${value}T00:00:00`);if(Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==value)return false;const now=new Date();let age=now.getFullYear()-date.getFullYear();if(now.getMonth()<date.getMonth()||(now.getMonth()===date.getMonth()&&now.getDate()<date.getDate()))age-=1;return age>=3&&age<=18;}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},authHero:{padding:38,paddingTop:65,alignItems:'center',borderBottomLeftRadius:35,borderBottomRightRadius:35},shield:{fontSize:58},authTitle:{color:colors.white,fontSize:31,fontWeight:'900',letterSpacing:2},authLead:{color:'#DDE8F6',marginTop:8},form:{width:'100%',maxWidth:480,alignSelf:'center',padding:25,gap:14},onboard:{flex:1,padding:28,justifyContent:'center',alignItems:'stretch',gap:16},heading:{fontSize:25,color:colors.navy,fontWeight:'900',textAlign:'center'},copy:{color:colors.muted,textAlign:'center'},privacyNote:{color:colors.muted,fontSize:11,marginTop:-10},input:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:15,fontSize:15,color:colors.ink},primary:{backgroundColor:colors.green,borderRadius:14,padding:16,alignItems:'center'},primaryDisabled:{opacity:.65},primaryText:{color:colors.white,fontWeight:'900'},message:{borderRadius:14,borderWidth:1,padding:13},successMessage:{backgroundColor:'#EAF5DF',borderColor:'#B9D998'},errorMessage:{backgroundColor:'#FCE9E6',borderColor:'#E6A69B'},messageText:{fontSize:12,lineHeight:18,fontWeight:'700'},successText:{color:'#315D1A'},errorText:{color:'#9A3528'},link:{color:colors.green,textAlign:'center',fontWeight:'800',padding:8},segment:{flexDirection:'row',backgroundColor:'#E7E2D7',padding:4,borderRadius:14},segmentItem:{flex:1,padding:12,alignItems:'center',borderRadius:11},segmentActive:{backgroundColor:colors.navy},segmentText:{color:colors.muted,fontWeight:'800'},segmentTextActive:{color:colors.white}});
