import { useState } from 'react';
import { Alert, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { supabase } from './lib/supabase';
import { colors } from './theme';

export function AuthScreen() {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [signup,setSignup]=useState(false); const [busy,setBusy]=useState(false);
  const submit=async()=>{ if(!supabase||!email||!password)return; setBusy(true); const result=signup?await supabase.auth.signUp({email,password,options:{data:{display_name:name}}}):await supabase.auth.signInWithPassword({email,password}); setBusy(false); if(result.error) Alert.alert('Could not continue',result.error.message); else if(signup&&!result.data.session) Alert.alert('Check your email','Confirm your email, then sign in.'); };
  return <SafeAreaView style={styles.safe}><LinearGradient colors={[colors.navy,'#294C7E']} style={styles.authHero}><Text style={styles.shield}>🛡️</Text><Text style={styles.authTitle}>HOME <Text style={{color:'#A7D66D'}}>HERO</Text></Text><Text style={styles.authLead}>Strong habits today. Success tomorrow.</Text></LinearGradient><View style={styles.form}><Text style={styles.heading}>{signup?'Create your hero account':'Welcome back'}</Text>{signup&&<TextInput placeholder="Display name" value={name} onChangeText={setName} style={styles.input}/>}<TextInput placeholder="Email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} style={styles.input}/><TextInput placeholder="Password" secureTextEntry value={password} onChangeText={setPassword} style={styles.input}/><Pressable onPress={submit} disabled={busy} style={styles.primary}><Text style={styles.primaryText}>{busy?'Please wait…':signup?'Create account':'Sign in'}</Text></Pressable><Pressable onPress={()=>setSignup(v=>!v)}><Text style={styles.link}>{signup?'Already have an account? Sign in':'New family? Create an account'}</Text></Pressable></View></SafeAreaView>;
}

export function OnboardingScreen({refresh}:{refresh:()=>Promise<void>}) {
  const [mode,setMode]=useState<'parent'|'child'>('parent'); const [value,setValue]=useState(''); const [birthDate,setBirthDate]=useState(''); const [busy,setBusy]=useState(false);
  const submit=async()=>{if(!supabase||!value.trim())return;if(mode==='child'&&!/^\d{4}-\d{2}-\d{2}$/.test(birthDate))return Alert.alert('Birth date required','Enter the Hero’s birth date as YYYY-MM-DD so quests can be age appropriate.');setBusy(true);if(mode==='child'){const {data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return;}const {error:profileError}=await supabase.from('profiles').update({date_of_birth:birthDate}).eq('id',user.id);if(profileError){setBusy(false);return Alert.alert('Could not save birth date',profileError.message);}}const {error}=mode==='parent'?await supabase.rpc('create_parent_household',{p_name:value.trim(),p_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone}):await supabase.rpc('join_household_as_child',{p_invite_code:value.trim()});setBusy(false);if(error)Alert.alert('Could not continue',error.message);else await refresh();};
  return <SafeAreaView style={styles.safe}><View style={styles.onboard}><Text style={styles.shield}>🛡️</Text><Text style={styles.heading}>Build your hero party</Text><Text style={styles.copy}>Choose how this account will use Home Hero.</Text><View style={styles.segment}>{(['parent','child'] as const).map(item=><Pressable key={item} onPress={()=>setMode(item)} style={[styles.segmentItem,mode===item&&styles.segmentActive]}><Text style={[styles.segmentText,mode===item&&styles.segmentTextActive]}>{item==='parent'?'Party Leader':'Hero'}</Text></Pressable>)}</View><TextInput value={value} onChangeText={setValue} autoCapitalize={mode==='child'?'characters':'words'} placeholder={mode==='parent'?'Family name':'8-character family code'} style={styles.input}/>{mode==='child'&&<><TextInput value={birthDate} onChangeText={setBirthDate} keyboardType="numbers-and-punctuation" placeholder="Birth date · YYYY-MM-DD" style={styles.input}/><Text style={styles.privacyNote}>Used only to show age-appropriate quests.</Text></>}<Pressable onPress={submit} disabled={busy} style={styles.primary}><Text style={styles.primaryText}>{busy?'Setting up…':mode==='parent'?'Create family':'Join family'}</Text></Pressable><Pressable onPress={()=>supabase?.auth.signOut()}><Text style={styles.link}>Sign out</Text></Pressable></View></SafeAreaView>;
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},authHero:{padding:38,paddingTop:65,alignItems:'center',borderBottomLeftRadius:35,borderBottomRightRadius:35},shield:{fontSize:58},authTitle:{color:colors.white,fontSize:31,fontWeight:'900',letterSpacing:2},authLead:{color:'#DDE8F6',marginTop:8},form:{padding:25,gap:14},onboard:{flex:1,padding:28,justifyContent:'center',alignItems:'stretch',gap:16},heading:{fontSize:25,color:colors.navy,fontWeight:'900',textAlign:'center'},copy:{color:colors.muted,textAlign:'center'},privacyNote:{color:colors.muted,fontSize:11,marginTop:-10},input:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:15,fontSize:15,color:colors.ink},primary:{backgroundColor:colors.green,borderRadius:14,padding:16,alignItems:'center'},primaryText:{color:colors.white,fontWeight:'900'},link:{color:colors.green,textAlign:'center',fontWeight:'800',padding:8},segment:{flexDirection:'row',backgroundColor:'#E7E2D7',padding:4,borderRadius:14},segmentItem:{flex:1,padding:12,alignItems:'center',borderRadius:11},segmentActive:{backgroundColor:colors.navy},segmentText:{color:colors.muted,fontWeight:'800'},segmentTextActive:{color:colors.white}});
